/*
 * File: app/store/DayRoundTreeStore.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('inficare.store.DayRoundTreeStore', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'inficare.model.VisitModel'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'inficare.model.VisitModel',
            storeId: 'DayRoundStore',
            folderSort: true,
            proxy: {
                type: 'ajax',
                url: 'resources/data/tree/treegrid2.json',
                listeners: {
                    exception: {
                        fn: me.onAjaxException,
                        scope: me
                    }
                }
            }
        }, cfg)]);
    },

    onAjaxException: function(proxy, response, operation, eOpts) {
        console.log(response,operation);
    }

});