/*
 * File: app/store/PatientStore.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('inficare.store.PatientStore', {
    extend: 'Ext.data.Store',

    requires: [
        'inficare.model.PatientModel',
        'inficare.DirectAPI',
        'Ext.data.proxy.Direct'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            autoSync: true,
            model: 'inficare.model.PatientModel',
            storeId: 'patientStoreId',
            proxy: {
                type: 'direct',
                api: {
                    create: QueryPatientsDb.createRecord,
                    read: QueryPatientsDb.getResults,
                    update: QueryPatientsDb.updateRecords,
                    destroy: QueryPatientsDb.destroyRecord
                },
                idParam: 'idp'
            }
        }, cfg)]);
    }
});