/*
 * File: app/view/EditMail.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('inficare.view.EditMail', {
    extend: 'Ext.window.Window',
    alias: 'widget.editmail',

    requires: [
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Spacer',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea'
    ],

    height: 296,
    width: 582,
    layout: 'fit',
    title: 'Edition mail',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            layout: {
                                type: 'hbox',
                                pack: 'center'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'sendMailBtnId',
                                    glyph: 'xe011@fcrooks',
                                    text: 'Envoyer'
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 30
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'cancelEditMailBtnId',
                                    glyph: 'xe015@fcrooks',
                                    text: 'Abandonner'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Destinatiares Supplémentaires',
                            labelWidth: 200,
                            name: 'nurselist',
                            displayField: 'namen',
                            multiSelect: true,
                            store: 'NurseStore',
                            valueField: 'idn'
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            height: 170,
                            fieldLabel: 'Message',
                            name: 'message'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});