/*
 * File: app/view/EditPatientListView.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('inficare.view.EditPatientListView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.editpatientlistview',

    height: 520,
    width: 880,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    header: false,
    title: 'Edit Patients List',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    itemId: 'patientGridId',
                    header: false,
                    title: 'My Grid Panel',
                    store: 'PatientStore',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            itemId: 'fulPatientSearchTbId',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'saveFullPatientBtnId',
                                    glyph: 'xe00d@fcrooks',
                                    text: 'Sauver'
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 20
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'addFullPatientBtnId',
                                    glyph: 'xe012@fcrooks',
                                    text: 'Nouveau patient'
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 10
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'delFullPatientBtnId',
                                    glyph: 'xe00e@fcrooks',
                                    text: 'Effacer patient'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'textfield',
                                    itemId: 'searchFullPatientFldId',
                                    fieldLabel: 'Recherche'
                                }
                            ]
                        }
                    ],
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'namep',
                            text: 'Nom',
                            flex: 1,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'address',
                            text: 'Adresse',
                            flex: 2,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'tel',
                            text: 'Tél',
                            flex: 1,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'care',
                            text: 'Soin',
                            flex: 3,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'infop',
                            text: 'Détail',
                            flex: 3,
                            editor: {
                                xtype: 'textfield'
                            }
                        },
                        {
                            xtype: 'checkcolumn',
                            width: 40,
                            dataIndex: 'activep',
                            hideable: false,
                            menuDisabled: true,
                            text: 'Actif',
                            editor: {
                                xtype: 'checkboxfield'
                            }
                        }
                    ],
                    plugins: [
                        Ext.create('Ext.grid.plugin.RowEditing', {
                            pluginId: 'rowEditFullPatientId',
                            autoCancel: false
                        })
                    ],
                    selModel: Ext.create('Ext.selection.RowModel', {

                    })
                }
            ]
        });

        me.callParent(arguments);
    }

});