/*
 * File: app/view/InfiMainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('inficare.view.InfiMainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.infimainview',

    requires: [
        'inficare.view.EditDayRoundView',
        'inficare.view.EditPatientListView',
        'inficare.view.ReportView',
        'Ext.form.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.toolbar.Fill',
        'Ext.toolbar.TextItem'
    ],

    layout: 'fit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    itemId: 'inficareCardWsId',
                    layout: 'card',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Compte',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'loginMenuId',
                                                glyph: 'xe00b@fcrooks',
                                                text: 'Connexion'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                disabled: true,
                                                itemId: 'logoffMenuId',
                                                text: 'Deconnexion'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'editionMenuId',
                                    text: 'Edition',
                                    menu: {
                                        xtype: 'menu',
                                        width: 120,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'editRoundMenuId',
                                                text: 'Tournée'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'editPatientMenuId',
                                                text: 'Patients'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                itemId: 'reportMenuId',
                                                text: 'Rapports'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'editRoundBtnId',
                                    glyph: 'xe018@fcrooks',
                                    text: 'Tournée'
                                },
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'editPatientBtnId',
                                    glyph: 'xe016@fcrooks',
                                    text: 'Patients'
                                },
                                {
                                    xtype: 'button',
                                    disabled: true,
                                    itemId: 'reportBtnId',
                                    glyph: 'xe017@fcrooks',
                                    text: 'Rapports'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'tbtext',
                                    style: 'font-size:8pt;color:#A0A0A0;',
                                    text: 'v. 2.1'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'component',
                            itemId: 'logoffViewId'
                        },
                        {
                            xtype: 'editdayroundview',
                            itemId: 'editRoundViewId',
                            title: 'Edit Round View'
                        },
                        {
                            xtype: 'editpatientlistview',
                            itemId: 'editPatientsListId'
                        },
                        {
                            xtype: 'reportview',
                            itemId: 'reportViewId'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});