/*
 * File: app/view/ReportView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('inficare.view.ReportView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.reportview',

    header: false,
    title: 'My Panel',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: 'Paramètres généraux',
                    items: [
                        {
                            xtype: 'datefield',
                            itemId: 'mainDateId',
                            fieldLabel: 'Date:',
                            editable: false,
                            format: 'd/m/Y'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    height: 133,
                    itemId: 'dayRoundFormId',
                    bodyPadding: 10,
                    title: 'Tournée du jour',
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            height: 69,
                            width: 398,
                            fieldLabel: 'Label',
                            hideLabel: true,
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'dayRoundDateFldId',
                                    fieldLabel: 'Date configurée',
                                    name: 'visitDate',
                                    readOnly: true
                                },
                                {
                                    xtype: 'radiogroup',
                                    itemId: 'operationGroupId',
                                    margin: '0 10 10 0',
                                    width: 398,
                                    fieldLabel: 'Opération',
                                    items: [
                                        {
                                            xtype: 'radiofield',
                                            name: 'operation',
                                            boxLabel: 'Télécharger',
                                            checked: true,
                                            inputValue: 'download'
                                        },
                                        {
                                            xtype: 'radiofield',
                                            name: 'operation',
                                            boxLabel: 'Email',
                                            inputValue: 'email'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'dayRoundExecuteBtnId',
                                    width: 108,
                                    glyph: 'xe013@fcrooks',
                                    text: 'Exécuter'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'form',
                    itemId: 'tarifFormId',
                    bodyPadding: 10,
                    title: 'Tarification',
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            height: 54,
                            width: 366,
                            fieldLabel: 'Label',
                            hideLabel: true,
                            items: [
                                {
                                    xtype: 'textfield',
                                    itemId: 'tarifDateFldId',
                                    fieldLabel: 'Mois configuré'
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            itemId: 'tarifExecuteBtnId',
                            width: 109,
                            glyph: 'xe013@fcrooks',
                            text: 'Exécuter'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    downloadFile: function(sUrl) {
        //If in Chrome or Safari - download via virtual link click
        if (Ext.isChrome || Ext.isSafari)
        {
            //Creating new link node.
            var link = document.createElement('a');
            link.href = sUrl;

            if (link.download !== undefined)
            {
                //Set HTML5 download attribute. This will prevent file from opening if supported.
                var fileName = sUrl.substring(sUrl.lastIndexOf('/') + 1, sUrl.length);
                link.download = fileName;
            }

            //Dispatching click event.
            if (document.createEvent)
            {
                var e = document.createEvent('MouseEvents');
                e.initEvent('click' ,true ,true);
                link.dispatchEvent(e);
                return true;
            }
        }

        // Force file download (whether supported by server).
        var query = '?download';

        window.open(sUrl + query);
    }

});