/*
 * File: app/view/RoundSource.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('inficare.view.RoundSource', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.roundsource',

    height: 787,
    itemId: 'dayRoundSource',
    width: 1023,
    collapsible: false,
    header: false,
    title: 'Elements de tournée',
    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    itemId: 'drsPatientListId',
                    layout: {
                        type: 'fit'
                    },
                    title: 'Liste patients',
                    tabConfig: {
                        xtype: 'tab',
                        handleMouseEvents: false
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            itemId: 'patientVisitGridId',
                            header: false,
                            title: 'Patients List',
                            forceFit: false,
                            store: 'VisitPatientStore',
                            dockedItems: [
                                {
                                    xtype: 'toolbar',
                                    dock: 'top',
                                    itemId: 'patientSearchTbId',
                                    items: [
                                        {
                                            xtype: 'button',
                                            itemId: 'refreshPatientVisitBtnId',
                                            glyph: 'xe00a@fcrooks',
                                            text: 'Raffraîchir'
                                        },
                                        {
                                            xtype: 'tbfill'
                                        },
                                        {
                                            xtype: 'textfield',
                                            itemId: 'searchPatientFldId',
                                            fieldLabel: 'Recherche',
                                            name: 'searchPatient'
                                        },
                                        {
                                            xtype: 'button',
                                            hidden: true,
                                            itemId: 'searchPatientBtnId',
                                            text: 'Go'
                                        }
                                    ]
                                }
                            ],
                            viewConfig: {
                                itemId: 'patientVisitViewId',
                                plugins: [
                                    Ext.create('Ext.grid.plugin.DragDrop', {
                                        ddGroup: 'dayVisitDd',
                                        dragText: 'Drag & drop vers tournée',
                                        enableDrop: false
                                    })
                                ]
                            },
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'namev',
                                    menuDisabled: true,
                                    text: 'Patient Name',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'patientcare',
                                    menuDisabled: true,
                                    text: 'Soins',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'patientinfo',
                                    menuDisabled: true,
                                    text: 'Détail',
                                    flex: 1
                                }
                            ],
                            selModel: Ext.create('Ext.selection.RowModel', {
                                mode: 'SINGLE'
                            })
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    itemId: 'drsRefRoundId',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    title: 'Tournée de référence',
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'copyAllRoundBtnId',
                                    glyph: 'xe0014@fcrooks',
                                    text: 'Copier tout'
                                },
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'datefield',
                                    itemId: 'refVisitDateFildId',
                                    fieldLabel: 'Label',
                                    editable: false,
                                    format: 'd/m/Y'
                                }
                            ]
                        }
                    ],
                    items: [
                        {
                            xtype: 'treepanel',
                            flex: 1,
                            height: 250,
                            itemId: 'refDayVisitTree',
                            width: 400,
                            animCollapse: false,
                            header: false,
                            title: 'Ref Day Visit List',
                            hideHeaders: false,
                            store: 'RefVisitTreeStore',
                            animate: false,
                            rootVisible: false,
                            viewConfig: {
                                itemId: 'refDayTreeViewId',
                                rootVisible: false,
                                plugins: [
                                    Ext.create('Ext.tree.plugin.TreeViewDragDrop', {
                                        ddGroup: 'dayVisitDd',
                                        dragText: 'Drag & drop pour réorganiser'
                                    })
                                ]
                            },
                            columns: [
                                {
                                    xtype: 'treecolumn',
                                    minWidth: 200,
                                    width: 200,
                                    sortable: false,
                                    dataIndex: 'namev',
                                    menuDisabled: true,
                                    text: 'Visite'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        var cstore = Ext.getStore("NurseStore");
                                        var idx;

                                        if (value<=0)
                                        return "";
                                        else
                                        {
                                            idx = cstore.findExact('idn',value);

                                            if(idx<0)
                                            return "";
                                            else
                                            {
                                                var rec = cstore.getAt(idx);
                                                return rec.get('namen');
                                            }
                                        }

                                    },
                                    width: 100,
                                    sortable: false,
                                    dataIndex: 'nurseid',
                                    menuDisabled: true,
                                    text: 'Soignant'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    sortable: false,
                                    dataIndex: 'patientinfo',
                                    menuDisabled: true,
                                    text: 'Détail',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    sortable: false,
                                    dataIndex: 'patientcare',
                                    menuDisabled: true,
                                    text: 'Soins',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        return value.replace(/<\/?[^>]+(>|$)/g, " ");

                                    },
                                    sortable: false,
                                    dataIndex: 'visitinfo',
                                    menuDisabled: true,
                                    text: 'Info visite',
                                    flex: 2
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});