/*
 * File: app/view/VisitInfoEdit.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('inficare.view.VisitInfoEdit', {
    extend: 'Ext.window.Window',
    alias: 'widget.visitinfoedit',

    height: 250,
    width: 616,
    layout: {
        type: 'fit'
    },
    closable: false,
    title: 'Edition Info Visite',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 161,
                    itemId: 'visitInfoFormId',
                    layout: {
                        type: 'fit'
                    },
                    bodyPadding: 0,
                    header: false,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'textareafield',
                            height: 150,
                            name: 'visitinfo'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            layout: {
                                pack: 'center',
                                type: 'hbox'
                            },
                            items: [
                                {
                                    xtype: 'button',
                                    itemId: 'saveId',
                                    text: 'Modifier'
                                },
                                {
                                    xtype: 'tbspacer',
                                    width: 20
                                },
                                {
                                    xtype: 'button',
                                    itemId: 'cancelId',
                                    text: 'Annuler'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});