/*
 * File: app/model/PatientModel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('inficare.model.PatientModel', {
    extend: 'Ext.data.Model',
    alias: 'model.patientmodel',

    requires: [
        'Ext.data.Field'
    ],

    idProperty: 'idp',

    fields: [
        {
            name: 'idp',
            type: 'int'
        },
        {
            name: 'activep',
            type: 'boolean'
        },
        {
            name: 'namep',
            type: 'string'
        },
        {
            name: 'address',
            type: 'string'
        },
        {
            name: 'tel',
            type: 'string'
        },
        {
            name: 'infop',
            type: 'string'
        },
        {
            name: 'care',
            type: 'string'
        }
    ]
});