/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({
    disableCaching: false,
    enabled: true
});


Ext.application({

    requires: [
        'Ext.Loader',
        'Ext.direct.*',
        'Ext.data.*',
        'Ext.form.*'
    ],
    models: [
        'NurseModel',
        'PatientModel',
        'VisitModel'
    ],
    stores: [
        'DayRoundTreeStore',
        'VisitEditTreeStore',
        'VisitPatientStore',
        'NurseStore',
        'PatientStore',
        'RefVisitTreeStore'
    ],
    views: [
        'InfiMainView',
        'EditDayRoundView',
        'DayEditView',
        'EditPatientListView',
        'RoundSource',
        'ReportView',
        'EditMail'
    ],
    controllers: [
        'DayRoundController',
        'MainController',
        'PatientEditController',
        'ReportController'
    ],
    name: 'inficare',

    launch: function() {
        Ext.create('inficare.view.InfiMainView');
        //The Ext.app.REMOTING_API variable is defined by the inclusion of the php/api.php script from the application
        //main html page.
        Ext.direct.Manager.addProvider(Ext.app.REMOTING_API);

    }

});
