
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../ext/src",
  "Ext.DomHelper": "../../ext/src/dom/Helper.js",
  "Ext.DomQuery": "../../ext/src/dom/Query.js",
  "Ext.EventObjectImpl": "../../ext/src/EventObject.js",
  "Ext.Msg": "../../ext/src/window/MessageBox.js",
  "Ext.Supports": "../../ext/src/Support.js",
  "Ext.core.DomHelper": "../../ext/src/dom/Helper.js",
  "Ext.core.DomQuery": "../../ext/src/dom/Query.js",
  "Ext.rtl.EventObjectImpl": "../../ext/src/rtl/EventObject.js",
  "inficare": "../../app",
  "test5": "../../app",
  "test5.Application": "../../app/application.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "inficare.controller.DayRoundController": [],
  "inficare.controller.MainController": [],
  "inficare.controller.PatientEditController": [],
  "inficare.controller.ReportController": [],
  "inficare.direct": [],
  "inficare.model.NurseModel": [],
  "inficare.model.PatientModel": [],
  "inficare.model.VisitModel": [],
  "inficare.override.window.Window": [],
  "inficare.store.DayRoundTreeStore": [],
  "inficare.store.NurseStore": [],
  "inficare.store.PatientStore": [],
  "inficare.store.RefVisitTreeStore": [],
  "inficare.store.VisitEditTreeStore": [],
  "inficare.store.VisitPatientStore": [],
  "inficare.view.DayEditView": [],
  "inficare.view.EditDayRoundView": [],
  "inficare.view.EditMail": [],
  "inficare.view.EditPatientListView": [],
  "inficare.view.InfiMainView": [],
  "inficare.view.LoginView": [],
  "inficare.view.ReportView": [],
  "inficare.view.RoundSource": [],
  "inficare.view.Viewport": [],
  "inficare.view.VisitInfoEdit": [],
  "test5.Application": [],
  "test5.controller.Main": [],
  "test5.view.Main": []
});
Ext.ClassManager.addNameAliasMappings({
  "inficare.controller.DayRoundController": [],
  "inficare.controller.MainController": [],
  "inficare.controller.PatientEditController": [],
  "inficare.controller.ReportController": [],
  "inficare.direct": [],
  "inficare.model.NurseModel": [
    "model.nursemodel"
  ],
  "inficare.model.PatientModel": [
    "model.patientmodel"
  ],
  "inficare.model.VisitModel": [
    "model.visitmodel"
  ],
  "inficare.override.window.Window": [],
  "inficare.store.DayRoundTreeStore": [],
  "inficare.store.NurseStore": [],
  "inficare.store.PatientStore": [],
  "inficare.store.RefVisitTreeStore": [],
  "inficare.store.VisitEditTreeStore": [],
  "inficare.store.VisitPatientStore": [],
  "inficare.view.DayEditView": [
    "widget.dayeditview"
  ],
  "inficare.view.EditDayRoundView": [
    "widget.editdayroundview"
  ],
  "inficare.view.EditMail": [
    "widget.editmail"
  ],
  "inficare.view.EditPatientListView": [
    "widget.editpatientlistview"
  ],
  "inficare.view.InfiMainView": [
    "widget.infimainview"
  ],
  "inficare.view.LoginView": [
    "widget.loginview"
  ],
  "inficare.view.ReportView": [
    "widget.reportview"
  ],
  "inficare.view.RoundSource": [
    "widget.roundsource"
  ],
  "inficare.view.Viewport": [],
  "inficare.view.VisitInfoEdit": [
    "widget.visitinfoedit"
  ],
  "test5.Application": [],
  "test5.controller.Main": [],
  "test5.view.Main": [
    "widget.app-main"
  ]
});
