
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  " Ext.Msg": "../../ext/src/window/MessageBox.js",
  "Ext": "../../ext/src",
  "test5.Application": "../../app/application.js",
  "inficare": "../../app",
  "Ext.rtl.EventObjectImpl": "../../ext/src/rtl/EventObject.js",
  "test5": "../../app"
});
Ext.ClassManager.addNameAlternateMappings({
  "inficare.model.NurseModel": [],
  "inficare.store.VisitEditTreeStore": [],
  "inficare.store.NurseStore": [],
  "inficare.store.RefVisitTreeStore": [],
  "inficare.controller.ReportController": [],
  "inficare.store.VisitPatientStore": [],
  "inficare.controller.PatientEditController": [],
  "inficare.view.VisitInfoEdit": [],
  "inficare.controller.DayRoundController": [],
  "inficare.view.ReportView": [],
  "inficare.view.RoundSource": [],
  "test5.controller.Main": [],
  "test5.Application": [],
  "inficare.view.DayEditView": [],
  "inficare.controller.MainController": [],
  "inficare.view.EditMail": [],
  "inficare.model.PatientModel": [],
  "inficare.store.PatientStore": [],
  "inficare.model.VisitModel": [],
  "inficare.view.EditDayRoundView": [],
  "test5.view.Main": [],
  "inficare.view.Viewport": [],
  "inficare.view.InfiMainView": [],
  "inficare.view.EditPatientListView": [],
  "inficare.store.DayRoundTreeStore": [],
  "inficare.override.window.Window": [],
  "inficare.view.LoginView": []
});
Ext.ClassManager.addNameAliasMappings({
  "inficare.model.NurseModel": [
    "model.nursemodel"
  ],
  "inficare.store.VisitEditTreeStore": [],
  "inficare.store.NurseStore": [],
  "inficare.store.RefVisitTreeStore": [],
  "inficare.controller.ReportController": [],
  "inficare.store.VisitPatientStore": [],
  "inficare.controller.PatientEditController": [],
  "inficare.view.VisitInfoEdit": [
    "widget.visitinfoedit"
  ],
  "inficare.controller.DayRoundController": [],
  "inficare.view.ReportView": [
    "widget.reportview"
  ],
  "inficare.view.RoundSource": [
    "widget.roundsource"
  ],
  "test5.controller.Main": [],
  "test5.Application": [],
  "inficare.view.DayEditView": [
    "widget.dayeditview"
  ],
  "inficare.controller.MainController": [],
  "inficare.view.EditMail": [
    "widget.editmail"
  ],
  "inficare.model.PatientModel": [
    "model.patientmodel"
  ],
  "inficare.store.PatientStore": [],
  "inficare.model.VisitModel": [
    "model.visitmodel"
  ],
  "inficare.view.EditDayRoundView": [
    "widget.editdayroundview"
  ],
  "test5.view.Main": [
    "widget.app-main"
  ],
  "inficare.view.Viewport": [],
  "inficare.view.InfiMainView": [
    "widget.infimainview"
  ],
  "inficare.view.EditPatientListView": [
    "widget.editpatientlistview"
  ],
  "inficare.store.DayRoundTreeStore": [],
  "inficare.override.window.Window": [],
  "inficare.view.LoginView": [
    "widget.loginview"
  ]
});
