/*
 * File: app/controller/ReportController.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('inficare.controller.ReportController', {
    extend: 'Ext.app.Controller',

    onDayReportBtnClick: function(button, e, eOpts) {

        var formPanel = button.up('#dayRoundFormId');
        var form = formPanel.getForm();
        var operationGroup = formPanel.down('#operationGroupId');

        var visitDate = form.findField('visitDate').getValue();
        var operation = operationGroup.getValue();
        var dt = new Date();

        dt = Ext.Date.parse(visitDate, "d/m/Y");
        var visitDateReq = Ext.Date.format(dt,"Y-m-d");

        if (operation.operation == "email")
        {
            var editMail = this.editMail || (this.editMail = Ext.create('widget.editmail'));
            form = editMail.down('form');
            editMail.visitDateReq = visitDateReq;

            //    form.getForm().reset();
            //form.loadRecord(e.record);
            editMail.show();

        }
        else
        {
            var request = 'php/dayReport.php?'+Ext.Object.toQueryString({visitDate:visitDateReq, email:false});

            console.log('request:',request);

            this.downloadFile(request);
        }

    },

    onMainDateIdChange: function(field, newValue, oldValue, eOpts) {
        var reportView = Ext.ComponentQuery.query('reportview')[0]
        var dt = field.getValue();
        var dayRoundDateFld = reportView.down('#dayRoundDateFldId');
        var tarifDateFld    = reportView.down('#tarifDateFldId');

        dayRoundDateFld.setValue(Ext.Date.format(dt,'d/m/Y'));
        tarifDateFld.setValue(Ext.Date.format(dt,'m/Y'));
    },

    onSendMailBtnIdClick: function(button, e, eOpts) {
        var editMail = this.editMail;
        var form = editMail.down('form').getForm();
        var nurseList = form.findField('nurselist').getValue();
        var message = form.findField('message').getValue();


        editMail.hide();



        Ext.Ajax.request({
            url: 'php/dayReport.php',
            method: 'GET',
            params: {
                visitDate:editMail.visitDateReq,
                email:true,
                mailMessage: message,
                mailNurseList: nurseList.toString()
            },
            success: function(response){
                var res = Ext.JSON.decode(response.responseText, true);

                if (res)
                {
                    if (res.success)
                        Ext.Msg.alert('Exécuté', Ext.String.htmlEncode(res.message));
                    else
                        Ext.Msg.alert('ERREUR', Ext.String.htmlEncode(res.message));
                }
                else
                {
                    Ext.Msg.alert('Erreur', 'Echec d\'execution');
                }
            }
        });

    },

    onCancelEditMailBtnIdClick: function(button, e, eOpts) {
        var editMail = this.editMail;

        editMail.hide();

    },

    onTarifExecuteBtnIdClick: function(button, e, eOpts) {
        var reportView = Ext.ComponentQuery.query('reportview')[0]
        var formPanel = reportView.down('#tarifFormId');
        var form = formPanel.getForm();
        var tarifDateFld = reportView.down('#mainDateId');

        var visitDate = tarifDateFld.getValue();
        var visitDateReq = Ext.Date.format(visitDate,"Y-m-d");

        var request = 'php/zeTarifReport.php?'+Ext.Object.toQueryString({visitDate:visitDateReq});

        console.log('request:',request);

        this.downloadFile(request);

    },

    downloadFile: function(sUrl) {
        //If in Chrome or Safari - download via virtual link click
        if (Ext.isChrome || Ext.isSafari)
        {
            //Creating new link node.
            var link = document.createElement('a');
            link.href = sUrl;

            if (link.download !== undefined)
            {
                //Set HTML5 download attribute. This will prevent file from opening if supported.
                var fileName = sUrl.substring(sUrl.lastIndexOf('/') + 1, sUrl.length);
                link.download = fileName;
            }

            //Dispatching click event.
            if (document.createEvent)
            {
                var e = document.createEvent('MouseEvents');
                e.initEvent('click' ,true ,true);
                link.dispatchEvent(e);
                return true;
            }
        }

        // Force file download (whether supported by server).
        var query = '?download';

        window.open(sUrl + query);

    },

    setReportDate: function(date) {
        var reportView = Ext.ComponentQuery.query('reportview')[0]
        var dayRoundDateFld = reportView.down('#mainDateId');
        dayRoundDateFld.setValue(date);
    },

    init: function(application) {
        this.control({
            "#dayRoundExecuteBtnId": {
                click: this.onDayReportBtnClick
            },
            "#mainDateId": {
                change: this.onMainDateIdChange
            },
            "#sendMailBtnId": {
                click: this.onSendMailBtnIdClick
            },
            "#cancelEditMailBtnId": {
                click: this.onCancelEditMailBtnIdClick
            },
            "#tarifExecuteBtnId": {
                click: this.onTarifExecuteBtnIdClick
            }
        });
    }

});
